"use strict";

/* =========================================================
   TIẾNG ANH 2 - questions/tienganh2.js

   ĐÃ GHÉP LIST 11 → LIST 23

   Chức năng:
   1) Trắc nghiệm: hỏi TIẾNG ANH → chọn TIẾNG VIỆT
   2) Flashcard: TIẾNG ANH → TIẾNG VIỆT

   Tổng: 707 từ
========================================================= */

(function () {
    window.medQuizQuestions = window.medQuizQuestions || {};
    window.medQuizFlashcards = window.medQuizFlashcards || {};

    const vocabulary = [
        // ==================== LIST 11 ====================
        { en: "absent", vi: "Mất tích, không có mặt" },
        { en: "accumulate", vi: "tích lũy, gom góp" },
        { en: "adhere", vi: "tuân theo, tuân thủ" },
        { en: "appraisal", vi: "sự đánh giá, thẩm định" },
        { en: "apprentice", vi: "người học việc, người học nghề" },
        { en: "bankrupt", vi: "phá sản, vỡ nợ" },
        { en: "businessman", vi: "doanh nhân" },
        { en: "caution", vi: "lời cảnh báo, sự cảnh giác" },
        { en: "ceiling", vi: "trần nhà" },
        { en: "clip", vi: "cắt; cắt ngắn" },
        { en: "colorful", vi: "có nhiều màu sắc khác nhau, sặc sỡ" },
        { en: "compensate", vi: "trả tiền, trả thù lao" },
        { en: "comply", vi: "tuân theo, làm theo" },
        { en: "costume", vi: "trang phục" },
        { en: "diner", vi: "quán ăn rẻ tiền" },
        { en: "duplicate", vi: "nhân bản, sao chép" },
        { en: "eager", vi: "hăng hái, háo hức" },
        { en: "economist", vi: "nhà kinh tế học" },
        { en: "editorial", vi: "bài xã luận" },
        { en: "effectiveness", vi: "tính hiệu quả, tính hữu hiệu" },
        { en: "expiration", vi: "sự hết hạn, sự kết thúc" },
        { en: "facilitate", vi: "tạo điều kiện thuận lợi" },
        { en: "firefighter", vi: "lính cứu hỏa" },
        { en: "gasoline", vi: "dầu xăng" },
        { en: "headache", vi: "đau đầu" },
        { en: "inappropriate", vi: "không thích hợp, không thích đáng" },
        { en: "internet", vi: "mạng internet" },
        { en: "jam", vi: "nhồi nhét, ấn chặt" },
        { en: "landlord", vi: "chủ nhà" },
        { en: "layout", vi: "sự sắp đặt, dàn bài tổng thể" },
        { en: "lunchtime", vi: "giờ ăn trưa" },
        { en: "nail", vi: "đinh" },
        { en: "optimistic", vi: "lạc quan, tích cực" },
        { en: "payroll", vi: "tổng lương" },
        { en: "pedestrian", vi: "người đi bộ" },
        { en: "pharmaceutical", vi: "liên quan đến dược phẩm hoặc liên quan đến việc mua bán, sử dụng thuốc" },
        { en: "plausible", vi: "hợp lý" },
        { en: "premium", vi: "khoản tiền trả thêm" },
        { en: "projection", vi: "sự dự đoán về tương lai" },
        { en: "safely", vi: "một cách an toàn" },
        { en: "simplify", vi: "đơn giản hóa" },
        { en: "sleeve", vi: "tay áo" },
        { en: "solar", vi: "liên quan đến mặt trời" },
        { en: "specialty", vi: "chuyên môn" },
        { en: "suburb", vi: "ngoại ô" },
        { en: "takeover", vi: "sự mua lại để giành quyền kiểm soát công ty" },
        { en: "tech", vi: "từ viết tắt của technology - công nghệ" },
        { en: "unexpected", vi: "không ngờ tới" },
        { en: "unspecified", vi: "không xác định" },
        { en: "unsure", vi: "không chắc chắn" },
        { en: "upstairs", vi: "tầng trên, gác, lầu" },
        { en: "verbal", vi: "bằng lời nói, bằng miệng" },
        { en: "visa", vi: "thị thực" },
        { en: "wildlife", vi: "loài hoang dã" },
        { en: "workforce", vi: "lực lượng lao động" },

        // ==================== LIST 12 ====================
        { en: "accordingly", vi: "do đó, cho phù hợp" },
        { en: "apple", vi: "quả táo" },
        { en: "applicable", vi: "liên quan đến, thích hợp" },
        { en: "auction", vi: "buổi bán đấu giá" },
        { en: "balcony", vi: "ban công" },
        { en: "basement", vi: "tầng hầm" },
        { en: "beforehand", vi: "trước đó" },
        { en: "culinary", vi: "liên quan đến nấu ăn" },
        { en: "documentary", vi: "phim tài liệu" },
        { en: "downturn", vi: "sự suy thoái, sự suy giảm" },
        { en: "earthquake", vi: "động đất" },
        { en: "elegant", vi: "tao nhã, thanh lịch" },
        { en: "embassy", vi: "đại sứ quán" },
        { en: "excessive", vi: "quá mức, thừa" },
        { en: "fasten", vi: "buộc chặt" },
        { en: "generic", vi: "có tính chất chung" },
        { en: "harmful", vi: "gây tổn hại, đau đớn" },
        { en: "informative", vi: "cung cấp nhiều thông tin hữu ích" },
        { en: "institute", vi: "viện, học viện" },
        { en: "jazz", vi: "nhạc jazz" },
        { en: "kit", vi: "hộp dụng cụ, bộ đồ nghề" },
        { en: "lifetime", vi: "cả đời" },
        { en: "locally", vi: "bản địa, bản xứ, địa phương" },
        { en: "massage", vi: "xoa bóp, mát xa" },
        { en: "maximize", vi: "tận dụng tối đa, tối đa hóa" },
        { en: "mentor", vi: "người cố vấn hoặc giáo viên" },
        { en: "mild", vi: "nhẹ, êm dịu" },
        { en: "nominate", vi: "đề cử" },
        { en: "ongoing", vi: "vẫn đang xảy ra" },
        { en: "opt", vi: "lựa chọn" },
        { en: "parade", vi: "diễu hành, tuần hành" },
        { en: "periodically", vi: "định kỳ" },
        { en: "physician", vi: "bác sĩ" },
        { en: "pie", vi: "loại bánh nướng với vỏ bánh phủ một phần hay bao toàn bộ phần nhân bên trong" },
        { en: "plug", vi: "bịt lỗ bằng nút, nút lại" },
        { en: "polish", vi: "đánh bóng" },
        { en: "postage", vi: "bưu phí" },
        { en: "recreational", vi: "có tính chất giải trí, có tính chất tiêu khiển" },
        { en: "recruitment", vi: "sự tuyển dụng" },
        { en: "referee", vi: "trọng tài" },
        { en: "referral", vi: "sự giới thiệu, lời giới thiệu" },
        { en: "rehearse", vi: "diễn tập" },
        { en: "removal", vi: "sự di dời, sự di chuyển" },
        { en: "renown", vi: "sự nổi tiếng" },
        { en: "runner", vi: "người chạy bộ" },
        { en: "satisfactory", vi: "hài lòng, có thể chấp nhận được" },
        { en: "seasonal", vi: "theo mùa" },
        { en: "separately", vi: "một cách riêng biệt" },
        { en: "sock", vi: "tất" },
        { en: "spam", vi: "thư rác" },
        { en: "surf", vi: "lướt web" },
        { en: "timetable", vi: "kế hoạch, thời gian biểu" },
        { en: "turnover", vi: "doanh số, doanh thu" },
        { en: "unnecessary", vi: "không cần thiết" },
        { en: "vase", vi: "cái bình hoa" },

        // ==================== LIST 13 ====================
        { en: "aboard", vi: "trên hoặc trong một phương tiện di chuyển, ví dụ: trên thuyền" },
        { en: "acceptance", vi: "sự chấp nhận" },
        { en: "advancement", vi: "sự tiến bộ, sự thăng tiến" },
        { en: "advertiser", vi: "nhà quảng cáo" },
        { en: "allocate", vi: "phân công, phân phát" },
        { en: "alternatively", vi: "một cách khác, cách thay thế" },
        { en: "ambitious", vi: "có nhiều tham vọng" },
        { en: "amuse", vi: "giải trí" },
        { en: "appendix", vi: "phụ lục" },
        { en: "attorney", vi: "luật sư" },
        { en: "authorization", vi: "sự cho phép, sự ủy quyền để làm điều gì đó" },
        { en: "booth", vi: "gian hàng, buồng kín" },
        { en: "campus", vi: "khuôn viên trường đại học" },
        { en: "candy", vi: "món kẹo" },
        { en: "certify", vi: "chứng nhận, chứng thực" },
        { en: "checkout", vi: "sự trả phòng khách sạn" },
        { en: "chemistry", vi: "hóa học" },
        { en: "circulation", vi: "sự lưu hành" },
        { en: "clarify", vi: "giải thích hoặc làm rõ" },
        { en: "classmate", vi: "bạn học cùng lớp" },
        { en: "compile", vi: "biên soạn, thu thập dữ liệu" },
        { en: "concierge", vi: "nhân viên hỗ trợ tiền sảnh khách sạn" },
        { en: "consent", vi: "bằng lòng, tán thành, cho phép" },
        { en: "consistently", vi: "một cách nhất quán" },
        { en: "cookie", vi: "bánh quy" },
        { en: "correction", vi: "sự sửa chữa, sự hiệu chỉnh" },
        { en: "customize", vi: "tùy chỉnh" },
        { en: "deck", vi: "sân thượng" },
        { en: "dedication", vi: "sự cống hiến, sự tận tâm" },
        { en: "descriptive", vi: "dùng để diễn tả, mô tả" },
        { en: "detach", vi: "tháo ra, tách ra" },
        { en: "diagnose", vi: "chẩn đoán, phát hiện lỗi sai" },
        { en: "documentation", vi: "tài liệu" },
        { en: "entrepreneur", vi: "doanh nhân" },
        { en: "exceptional", vi: "phi thường, đặc biệt" },
        { en: "familiarize", vi: "làm cho quen thân" },
        { en: "hotline", vi: "đường dây nóng" },
        { en: "intonation", vi: "ngữ điệu" },
        { en: "invention", vi: "sự phát minh, sự sáng chế" },
        { en: "irritate", vi: "làm phiền" },
        { en: "locker", vi: "tủ nhỏ có khóa" },
        { en: "overlook", vi: "bỏ qua, không chú ý tới" },
        { en: "patent", vi: "bằng sáng chế, giấy phép độc quyền nhãn hiệu" },
        { en: "payable", vi: "có thể trả, phải trả" },
        { en: "preliminary", vi: "sơ bộ, bước đầu" },
        { en: "salesman", vi: "người bán hàng (nam giới)" },
        { en: "sauna", vi: "phòng tắm hơi" },
        { en: "smoothly", vi: "một cách êm ái, một cách trơn tru" },
        { en: "sunshine", vi: "ánh sáng mặt trời" },
        { en: "tow", vi: "kéo" },
        { en: "translator", vi: "người biên dịch" },
        { en: "tuition", vi: "học phí" },
        { en: "unavailable", vi: "không có sẵn" },
        { en: "violation", vi: "sự vi phạm" },
        { en: "webpage", vi: "trang web" },

        // ==================== LIST 14 ====================
        { en: "accent", vi: "giọng đặc trưng" },
        { en: "advisory", vi: "liên quan đến tư vấn, cố vấn" },
        { en: "asleep", vi: "ngủ, đang ngủ" },
        { en: "authentic", vi: "thật, xác thực, không phải là giả" },
        { en: "bakery", vi: "cửa hàng bánh" },
        { en: "carton", vi: "hộp bìa cứng, hộp đựng hàng" },
        { en: "compartment", vi: "gian, ngăn" },
        { en: "compatible", vi: "phù hợp, tương thích" },
        { en: "consumption", vi: "sự tiêu thụ" },
        { en: "conveniently", vi: "một cách dễ dàng, tiện lợi" },
        { en: "cosmetic", vi: "làm cho tốt hơn mà không thay đổi nó quá nhiều" },
        { en: "courtesy", vi: "sự lịch sự, sự nhã nhặn" },
        { en: "creativity", vi: "óc sáng tạo, tính sáng tạo" },
        { en: "criteria", vi: "tiêu chuẩn, chỉ tiêu" },
        { en: "disagreement", vi: "sự bất đồng ý kiến" },
        { en: "discontinue", vi: "ngừng, làm gián đoạn" },
        { en: "dishwasher", vi: "máy rửa chén" },
        { en: "drought", vi: "hạn hán" },
        { en: "economize", vi: "tiết kiệm tiền, tránh lãng phí" },
        { en: "entitle", vi: "quyền được tham gia, tham dự" },
        { en: "firework", vi: "pháo hoa" },
        { en: "freight", vi: "hàng hóa chuyên chở" },
        { en: "fry", vi: "chiên rán" },
        { en: "gallon", vi: "gallon, đơn vị đo lường chất lỏng" },
        { en: "gardener", vi: "người làm vườn" },
        { en: "ideally", vi: "trong lý tưởng, một cách lý tưởng" },
        { en: "inclusive", vi: "bao gồm tất cả mọi thứ" },
        { en: "insufficient", vi: "không đủ" },
        { en: "introductory", vi: "để giới thiệu, mở đầu" },
        { en: "junk", vi: "vật phẩm vô dụng, rác" },
        { en: "ma'am", vi: "thưa bà" },
        { en: "mileage", vi: "tổng số dặm đã đi được" },
        { en: "noisy", vi: "ồn ào" },
        { en: "pan", vi: "cái chảo" },
        { en: "parcel", vi: "kiện hàng" },
        { en: "pasta", vi: "mì ống" },
        { en: "periodical", vi: "tạp chí xuất bản định kỳ" },
        { en: "pill", vi: "thuốc dạng viên nén" },
        { en: "portable", vi: "có thể mang theo, xách tay" },
        { en: "punctual", vi: "đúng giờ" },
        { en: "recreation", vi: "thời gian rảnh rỗi" },
        { en: "relieve", vi: "làm dịu, làm mất đi" },
        { en: "reminder", vi: "cái làm nhớ lại một điều gì" },
        { en: "rumor", vi: "tin đồn" },
        { en: "scarf", vi: "khăn quàng cổ" },
        { en: "seaside", vi: "bờ biển" },
        { en: "shorten", vi: "rút ngắn" },
        { en: "specially", vi: "đặc biệt" },
        { en: "spill", vi: "làm đổ" },
        { en: "spouse", vi: "chồng, vợ" },
        { en: "subtract", vi: "trừ đi, lấy đi" },
        { en: "tablet", vi: "tấm, viên, thẻ, phiến" },
        { en: "ton", vi: "tấn" },
        { en: "vend", vi: "bán hàng hóa" },
        { en: "yoga", vi: "yoga" },

        // ==================== LIST 15 ====================
        { en: "absorb", vi: "tiếp nhận, ngâm, thấm" },
        { en: "administer", vi: "quản lý" },
        { en: "ample", vi: "quá đủ, quá nhiều, phong phú" },
        { en: "antique", vi: "đồ cổ, thường là đồ nội thất hoặc đồ trang sức" },
        { en: "bean", vi: "hạt đậu" },
        { en: "browse", vi: "đọc lướt qua, xem lướt qua" },
        { en: "bye", vi: "tạm biệt" },
        { en: "careless", vi: "bất cẩn, cẩu thả" },
        { en: "collector", vi: "nhà sưu tầm" },
        { en: "conform", vi: "làm cho phù hợp với, giống với" },
        { en: "congestion", vi: "sự tắc nghẽn" },
        { en: "contradiction", vi: "sự mâu thuẫn, sự trái ngược" },
        { en: "contrary", vi: "trái ngược" },
        { en: "diploma", vi: "bằng cấp, chứng chỉ" },
        { en: "disappointment", vi: "sự thất vọng" },
        { en: "dissatisfy", vi: "làm cho ai đó không hài lòng" },
        { en: "distributor", vi: "nhà phân phối" },
        { en: "dive", vi: "lặn xuống nước" },
        { en: "energetic", vi: "sống động, tràn đầy năng lượng" },
        { en: "enjoyable", vi: "thú vị, thích thú" },
        { en: "faculty", vi: "một người hướng dẫn hoặc giáo sư tại trường đại học" },
        { en: "favorable", vi: "thuận lợi, có triển vọng" },
        { en: "foreman", vi: "đốc công, kíp trưởng" },
        { en: "forum", vi: "diễn đàn" },
        { en: "founder", vi: "người sáng lập" },
        { en: "fundraise", vi: "gây quỹ" },
        { en: "graphics", vi: "đồ họa" },
        { en: "handy", vi: "hữu ích" },
        { en: "hazardous", vi: "nguy hiểm" },
        { en: "healthcare", vi: "chăm sóc sức khỏe" },
        { en: "humidity", vi: "độ ẩm" },
        { en: "immigration", vi: "sự nhập cư, sự di cư" },
        { en: "influential", vi: "có uy thế, có tầm ảnh hưởng" },
        { en: "nationwide", vi: "trên toàn quốc" },
        { en: "pad", vi: "tập giấy viết, vẽ" },
        { en: "paraphrase", vi: "diễn giải lại cùng một ý nghĩa nhưng sử dụng từ khác" },
        { en: "placement", vi: "sự bố trí, sắp đặt ở vị trí" },
        { en: "postal", vi: "thuộc bưu điện, gửi bằng bưu điện" },
        { en: "publicity", vi: "sự quảng cáo" },
        { en: "renter", vi: "người thuê nhà" },
        { en: "repairperson", vi: "thợ sửa chữa" },
        { en: "repeatedly", vi: "lặp đi lặp lại nhiều lần" },
        { en: "restroom", vi: "nhà vệ sinh" },
        { en: "silently", vi: "một cách yên tĩnh" },
        { en: "spa", vi: "một nơi bạn có thể đến để thư giãn và cải thiện sức khỏe" },
        { en: "spreadsheet", vi: "bảng tính" },
        { en: "stapler", vi: "cái dập ghim" },
        { en: "streamline", vi: "sắp xếp hợp lý hóa, tối ưu cho tốt hơn" },
        { en: "substantially", vi: "đáng kể" },
        { en: "teller", vi: "người thu ngân, nhân viên ngân hàng" },
        { en: "tidy", vi: "dọn dẹp ngăn nắp" },
        { en: "toll", vi: "một chi phí nhỏ bạn trả để sử dụng dịch vụ, ví dụ như phí cầu đường" },
        { en: "toner", vi: "mực máy in" },
        { en: "urgently", vi: "một cách cấp thiết" },
        { en: "walkway", vi: "đường dành cho người đi bộ" },

        // ==================== LIST 16 ====================
        { en: "amenity", vi: "cơ sở vật chất tiện nghi" },
        { en: "approximate", vi: "xấp xỉ, gần đúng với" },
        { en: "await", vi: "chờ đợi hoặc mong đợi một cái gì đó sẽ xảy ra" },
        { en: "barbecue", vi: "tiệc nướng ngoài trời" },
        { en: "beginner", vi: "người mới" },
        { en: "biology", vi: "sinh học" },
        { en: "blanket", vi: "tấm chăn, cái mền" },
        { en: "chairperson", vi: "người phụ trách một cuộc họp, chủ tọa" },
        { en: "charitable", vi: "từ thiện" },
        { en: "checkup", vi: "bài kiểm tra tổng quát" },
        { en: "cooler", vi: "máy làm lạnh, hộp giữ lạnh" },
        { en: "crane", vi: "máy trục, cần cẩu" },
        { en: "dealership", vi: "đại lý" },
        { en: "dependable", vi: "đáng tin cậy" },
        { en: "disconnect", vi: "cắt hoặc tách" },
        { en: "dispose", vi: "bỏ một thứ gì đó đi" },
        { en: "disrupt", vi: "làm gián đoạn và gây ra sự hỗn loạn" },
        { en: "dynamic", vi: "năng động, sôi nổi" },
        { en: "enthusiastically", vi: "một cách hăng hái, nhiệt tình" },
        { en: "environmentally", vi: "liên quan đến môi trường tự nhiên" },
        { en: "escalator", vi: "thang cuốn" },
        { en: "exotic", vi: "ngoại lai" },
        { en: "fabric", vi: "vật liệu, vải" },
        { en: "freelance", vi: "làm việc tự do" },
        { en: "generalization", vi: "sự tổng quát hóa, sự tổng hợp" },
        { en: "grill", vi: "vỉ nướng" },
        { en: "guidance", vi: "sự chỉ đạo, sự hướng dẫn" },
        { en: "gum", vi: "keo dán" },
        { en: "habitual", vi: "thường lệ, theo thói quen" },
        { en: "hesitant", vi: "do dự, lưỡng lự" },
        { en: "indicator", vi: "sự chỉ thị, tín hiệu" },
        { en: "individually", vi: "một cách riêng biệt, riêng lẻ" },
        { en: "internationally", vi: "trên bình diện quốc tế" },
        { en: "invaluable", vi: "vô giá" },
        { en: "junior", vi: "trẻ hơn; thứ hạng thấp hơn, cấp dưới" },
        { en: "lifestyle", vi: "lối sống, cách sống" },
        { en: "likewise", vi: "cũng như thế, cùng như thế" },
        { en: "messenger", vi: "người đưa tin" },
        { en: "morale", vi: "tinh thần, chí khí" },
        { en: "orchestra", vi: "ban nhạc" },
        { en: "organizational", vi: "có tổ chức" },
        { en: "outlook", vi: "quan điểm, cách nhìn nhận" },
        { en: "paperback", vi: "sách bìa mềm" },
        { en: "physics", vi: "vật lý học" },
        { en: "pole", vi: "một cây gậy dài" },
        { en: "puzzle", vi: "vấn đề khó giải quyết, vấn đề nan giải" },
        { en: "rebate", vi: "số tiền được chiết khấu" },
        { en: "recur", vi: "xảy ra một lần nữa" },
        { en: "reflexive", vi: "phản thân" },
        { en: "snowy", vi: "có tuyết rơi" },
        { en: "steak", vi: "miếng cá để nướng, miếng thịt để nướng" },
        { en: "sticker", vi: "hình dán" },
        { en: "telecommunication", vi: "viễn thông" },
        { en: "timely", vi: "kịp thời" },
        { en: "uncomfortable", vi: "không thoải mái hoặc không vui với một tình huống hoặc điều gì đó" },

        // ==================== LIST 17 ====================
        { en: "amateur", vi: "người mới bắt đầu, dân nghiệp dư" },
        { en: "ambassador", vi: "đại sứ, người đại diện" },
        { en: "anew", vi: "bắt đầu lại từ đầu, một lần nữa" },
        { en: "architectural", vi: "thuộc về kiến trúc" },
        { en: "attain", vi: "đạt được" },
        { en: "balloon", vi: "bóng bay" },
        { en: "blueprint", vi: "bản vẽ thiết kế" },
        { en: "bug", vi: "con bọ, côn trùng nhỏ" },
        { en: "cautious", vi: "cẩn thận, cảnh giác" },
        { en: "circuit", vi: "đường đi vòng quanh" },
        { en: "clap", vi: "vỗ tay" },
        { en: "commerce", vi: "thương mại, kinh doanh, công nghiệp" },
        { en: "convey", vi: "truyền đạt, truyền tải" },
        { en: "cord", vi: "dây cáp điện" },
        { en: "counselor", vi: "tham vấn, cố vấn" },
        { en: "debit", vi: "sự ghi nợ" },
        { en: "delicate", vi: "mỏng manh, dễ tổn thương" },
        { en: "dependence", vi: "sự phụ thuộc" },
        { en: "distraction", vi: "sự làm xao lãng" },
        { en: "downsize", vi: "giảm kích thước hoặc số lượng" },
        { en: "elephant", vi: "con voi" },
        { en: "enthusiasm", vi: "sự hăng hái, sự nhiệt tình" },
        { en: "enthusiast", vi: "người đam mê về điều gì đó" },
        { en: "evident", vi: "hiển nhiên, rõ ràng" },
        { en: "flexibility", vi: "tính linh hoạt, tính linh động" },
        { en: "flextime", vi: "hệ thống giờ làm việc linh hoạt" },
        { en: "fortunately", vi: "một cách may mắn" },
        { en: "freighter", vi: "tàu chở hàng" },
        { en: "generator", vi: "máy phát điện" },
        { en: "hallway", vi: "hành lang" },
        { en: "hamburger", vi: "bánh mì kẹp thịt xay" },
        { en: "hazard", vi: "mối nguy" },
        { en: "homeowner", vi: "chủ nhà, người sở hữu nhà" },
        { en: "imperative", vi: "rất quan trọng và khẩn cấp" },
        { en: "inflate", vi: "thổi phồng, bơm phồng" },
        { en: "insert", vi: "chèn vào, thêm vào" },
        { en: "lecturer", vi: "người hướng dẫn hoặc giảng viên đại học" },
        { en: "meaningful", vi: "có ý nghĩa hoặc mục đích" },
        { en: "memorize", vi: "ghi nhớ" },
        { en: "merchant", vi: "thương gia" },
        { en: "modification", vi: "sự điều chỉnh" },
        { en: "occupant", vi: "người cư trú, người sử dụng" },
        { en: "reproduce", vi: "sao chép lại, mô phỏng" },
        { en: "spray", vi: "xịt, phun" },
        { en: "staple", vi: "kim bấm" },
        { en: "strategic", vi: "thuộc về chiến lược" },
        { en: "stripe", vi: "vạch sọc" },
        { en: "teen", vi: "tuổi teen, độ tuổi nằm trong khoảng 13–19 tuổi" },
        { en: "tempt", vi: "xúi giục" },
        { en: "timer", vi: "thiết bị bấm giờ" },
        { en: "unload", vi: "dỡ hàng" },
        { en: "unusually", vi: "không bình thường" },
        { en: "vacate", vi: "để trống, di chuyển ra khỏi" },
        { en: "whale", vi: "cá voi" },
        { en: "wisely", vi: "một cách khôn khéo" },

        // ==================== LIST 18 ====================
        { en: "activate", vi: "bắt đầu hoặc khởi động một cái gì đó" },
        { en: "additionally", vi: "ngoài ra, thêm vào đó" },
        { en: "affirmative", vi: "khẳng định, quả quyết" },
        { en: "baker", vi: "thợ làm bánh" },
        { en: "brainstorm", vi: "buổi thảo luận để đưa ra nhiều ý tưởng nhanh chóng" },
        { en: "cage", vi: "chuồng, lồng" },
        { en: "cinema", vi: "một rạp chiếu phim" },
        { en: "collaboration", vi: "sự hợp tác" },
        { en: "condominium", vi: "căn hộ chung cư" },
        { en: "consecutive", vi: "liên tiếp, nối tiếp" },
        { en: "cordless", vi: "không dây" },
        { en: "deluxe", vi: "sang trọng, hạng sang" },
        { en: "desirable", vi: "đáng ao ước, đáng khát khao" },
        { en: "discrepancy", vi: "sự khác biệt, bất đồng" },
        { en: "dispatch", vi: "gửi đi" },
        { en: "drawback", vi: "nhược điểm của một cái gì đó" },
        { en: "dull", vi: "nhàm chán, không hứng thú" },
        { en: "economically", vi: "về mặt kinh tế" },
        { en: "evenly", vi: "một cách công bằng, ngang nhau" },
        { en: "excellence", vi: "sự xuất sắc, sự ưu tú" },
        { en: "exclusively", vi: "dành riêng, một cách độc quyền" },
        { en: "farewell", vi: "lời chào tạm biệt" },
        { en: "fatigue", vi: "sự mệt mỏi" },
        { en: "fiscal", vi: "thuộc tài chính, ngân sách" },
        { en: "fleet", vi: "hạm đội" },
        { en: "flour", vi: "bột, bột mì" },
        { en: "overcharge", vi: "tính phí quá mức" },
        { en: "oversee", vi: "giám sát" },
        { en: "petition", vi: "đơn thỉnh cầu, đơn kiến nghị" },
        { en: "pillow", vi: "gối" },
        { en: "popcorn", vi: "bỏng ngô" },
        { en: "pottery", vi: "đồ đất nung, đồ gốm sứ" },
        { en: "professionally", vi: "thành thạo, một cách chuyên nghiệp" },
        { en: "publicize", vi: "quảng cáo, làm cho mọi người biết" },
        { en: "ray", vi: "tia sáng" },
        { en: "redecorate", vi: "trang trí lại" },
        { en: "refinery", vi: "nhà máy tinh chế nguyên liệu thô" },
        { en: "refresh", vi: "làm nhẹ người, làm tỉnh táo" },
        { en: "refundable", vi: "có thể hoàn tiền" },
        { en: "reimbursement", vi: "sự hoàn lại số tiền đã tiêu" },
        { en: "reliability", vi: "sự đáng tin cậy" },
        { en: "reluctant", vi: "miễn cưỡng làm gì" },
        { en: "sewer", vi: "cống rãnh" },
        { en: "skate", vi: "trượt băng" },
        { en: "skateboard", vi: "ván trượt" },
        { en: "sleepy", vi: "buồn ngủ" },
        { en: "tailor", vi: "điều chỉnh để làm cho đáp ứng nhu cầu" },
        { en: "termination", vi: "sự kết thúc" },
        { en: "theft", vi: "hành vi trộm cắp" },
        { en: "thunderstorm", vi: "bão tố thường có mưa to, gió, sấm sét" },
        { en: "transmission", vi: "sự truyền đi" },
        { en: "transmit", vi: "truyền, phát" },
        { en: "unused", vi: "không sử dụng" },
        { en: "waive", vi: "từ bỏ, khước từ" },
        { en: "yen", vi: "đồng Yên" },

        // ==================== LIST 19 ====================
        { en: "adapter", vi: "bộ chuyển đổi" },
        { en: "advisable", vi: "nên, thích hợp, đáng theo" },
        { en: "archive", vi: "kho lưu trữ, nơi lưu trữ" },
        { en: "artistic", vi: "sáng tạo, giàu nghệ thuật" },
        { en: "assurance", vi: "sự chắc chắn, sự đảm bảo" },
        { en: "athletic", vi: "thuộc thể thao" },
        { en: "attire", vi: "quần áo" },
        { en: "auditor", vi: "kiểm toán viên, người kiểm tra sổ sách" },
        { en: "bankruptcy", vi: "sự phá sản, vỡ nợ" },
        { en: "bulk", vi: "với số lượng lớn, một đống" },
        { en: "butter", vi: "bơ" },
        { en: "centimeter", vi: "đơn vị đo xăng-ti-mét" },
        { en: "circulate", vi: "di chuyển trong một vòng tròn" },
        { en: "comb", vi: "chải để gỡ rối" },
        { en: "comfortably", vi: "làm một cái gì đó một cách dễ dàng, thoải mái" },
        { en: "fog", vi: "sương mù" },
        { en: "formally", vi: "một cách chính thức" },
        { en: "gram", vi: "đơn vị đo khối lượng gram" },
        { en: "handbook", vi: "sổ tay hướng dẫn" },
        { en: "headphone", vi: "tai nghe" },
        { en: "heater", vi: "lò sưởi, hệ thống sưởi" },
        { en: "helmet", vi: "mũ bảo hiểm" },
        { en: "hiker", vi: "người đi bộ đường dài" },
        { en: "homeless", vi: "vô gia cư" },
        { en: "lighter", vi: "nhẹ hơn" },
        { en: "loudly", vi: "làm ồn, một cách không yên tĩnh" },
        { en: "loyalty", vi: "sự trung thành" },
        { en: "microwave", vi: "lò vi sóng" },
        { en: "misidentify", vi: "nhận dạng nhầm" },
        { en: "neat", vi: "ngăn nắp, sạch sẽ" },
        { en: "nomination", vi: "sự đề cử, bổ nhiệm" },
        { en: "officially", vi: "chính thức" },
        { en: "outfit", vi: "một bộ trang phục, một set đồ" },
        { en: "pastry", vi: "bánh ngọt, bánh có nhân" },
        { en: "personalize", vi: "cá nhân hóa" },
        { en: "poorly", vi: "tệ, không đủ" },
        { en: "prestigious", vi: "có uy tín" },
        { en: "purser", vi: "người quản lý trên tàu thủy du khách" },
        { en: "reassure", vi: "cam đoan, đảm bảo" },
        { en: "resume", vi: "tiếp tục hoặc bắt đầu lại" },
        { en: "reunion", vi: "sự sum họp" },
        { en: "revolutionize", vi: "cách mạng hóa" },
        { en: "seafood", vi: "hải sản" },
        { en: "signify", vi: "biểu thị" },
        { en: "slot", vi: "cái khe" },
        { en: "steer", vi: "lái tàu thủy, ô tô" },
        { en: "sue", vi: "kiện" },
        { en: "superb", vi: "rất tốt" },
        { en: "traditionally", vi: "theo truyền thống" },
        { en: "tremendous", vi: "phi thường hoặc xuất sắc" },
        { en: "underway", vi: "đang xảy ra" },
        { en: "unpleasant", vi: "không đẹp, không thoải mái" },
        { en: "violin", vi: "vĩ cầm" },
        { en: "ward", vi: "phường, khu vực trong thành phố" },
        { en: "worthwhile", vi: "đáng giá" },

        // ==================== LIST 20 ====================
        { en: "compliance", vi: "hành động tuân theo các quy tắc" },
        { en: "contraction", vi: "sự co lại, sự thu nhỏ lại" },
        { en: "cookbook", vi: "một cuốn sách đưa ra hướng dẫn về cách chuẩn bị và nấu thức ăn" },
        { en: "cushion", vi: "cái đệm, cái nệm" },
        { en: "dose", vi: "liều lượng" },
        { en: "drum", vi: "cái trống" },
        { en: "embed", vi: "ẩn vào, đóng vào, gắn vào" },
        { en: "evacuate", vi: "sơ tán" },
        { en: "expedite", vi: "xúc tiến, đẩy nhanh" },
        { en: "extinguisher", vi: "bình chữa cháy" },
        { en: "familiarity", vi: "sự quen thuộc" },
        { en: "flaw", vi: "khuyết điểm, lỗi hỏng" },
        { en: "fluctuate", vi: "dao động, thay đổi bất thường" },
        { en: "fluent", vi: "lưu loát, trôi chảy" },
        { en: "honestly", vi: "thực sự, một cách thành thật" },
        { en: "housekeep", vi: "chăm sóc và dọn dẹp nhà cửa" },
        { en: "hurricane", vi: "bão nhiệt đới" },
        { en: "hygiene", vi: "vệ sinh" },
        { en: "integral", vi: "quan trọng, thiết yếu" },
        { en: "interactive", vi: "tương tác lẫn nhau" },
        { en: "interfere", vi: "can thiệp, xen vào" },
        { en: "kilogram", vi: "kilogram, một đơn vị trọng lượng" },
        { en: "layoff", vi: "hành động của chủ lao động đình chỉ hoặc chấm dứt công việc" },
        { en: "lightweight", vi: "nhẹ" },
        { en: "merit", vi: "xứng đáng" },
        { en: "necklace", vi: "vòng cổ, dây chuyền" },
        { en: "needy", vi: "những người nghèo và không có đủ để sống" },
        { en: "overpay", vi: "trả tiền quá cao" },
        { en: "pamphlet", vi: "một quyển sách nhỏ hay một tập sách chứa đựng những thông tin" },
        { en: "partial", vi: "một phần" },
        { en: "penalize", vi: "phạt" },
        { en: "pollute", vi: "làm ô nhiễm môi trường" },
        { en: "prescribe", vi: "ra lệnh, quy định, bắt phải" },
        { en: "probable", vi: "có thể nhưng không chắc chắn trở thành sự thật" },
        { en: "prominent", vi: "quan trọng" },
        { en: "rainfall", vi: "lượng mưa" },
        { en: "relocation", vi: "sự di dời đến một địa điểm mới" },
        { en: "residence", vi: "nơi cư trú" },
        { en: "retrieve", vi: "lấy lại" },
        { en: "rider", vi: "người lái" },
        { en: "rubber", vi: "cao su" },
        { en: "rug", vi: "thảm trải sàn" },
        { en: "salespeople", vi: "những người bán hàng" },
        { en: "sharply", vi: "một cách mạnh mẽ" },
        { en: "similarity", vi: "sự giống nhau" },
        { en: "someday", vi: "một thời điểm nào đó" },
        { en: "spectator", vi: "khán giả" },
        { en: "stereo", vi: "máy thu phát" },
        { en: "storeroom", vi: "nhà kho" },
        { en: "subsidize", vi: "trợ cấp" },
        { en: "suspicious", vi: "hoài nghi, nghi ngờ" },
        { en: "tasty", vi: "ngon" },
        { en: "terrific", vi: "tuyệt vời" },
        { en: "underground", vi: "dưới lòng đất" },
        { en: "unpaid", vi: "không lương" },

        // ==================== LIST 21 ====================
        { en: "accuracy", vi: "sự chính xác" },
        { en: "anyhow", vi: "dù sao, bên cạnh đó" },
        { en: "appetizer", vi: "món khai vị" },
        { en: "arc", vi: "một đường cong, giống như một phần của vòng tròn, hình cung" },
        { en: "audition", vi: "cuộc thử giọng, cuộc diễn thử" },
        { en: "backpack", vi: "ba lô" },
        { en: "ballroom", vi: "phòng khiêu vũ" },
        { en: "beneficial", vi: "có ích, có lợi" },
        { en: "biography", vi: "tiểu sử" },
        { en: "bound", vi: "bao quanh với một cái gì đó, để che chắn hoặc khoanh kín" },
        { en: "broom", vi: "cây chổi quét" },
        { en: "cheeseburger", vi: "một chiếc bánh hamburger với phô mai tan chảy trên đó" },
        { en: "chilly", vi: "se lạnh" },
        { en: "circus", vi: "một màn trình diễn sặc sỡ hoặc lộn xộn" },
        { en: "compliment", vi: "lời khen ngợi" },
        { en: "consignment", vi: "một lô hàng hàng hóa để giao hàng" },
        { en: "continental", vi: "thuộc lục địa, thuộc đất liền" },
        { en: "copyright", vi: "bản quyền" },
        { en: "countryside", vi: "vùng nông thôn" },
        { en: "demolish", vi: "hạ gục, phá hủy hoàn toàn" },
        { en: "departmental", vi: "thuộc phòng ban" },
        { en: "desperate", vi: "khẩn cấp, tuyệt vọng" },
        { en: "devastate", vi: "phá hủy hoàn toàn" },
        { en: "diagnostic", vi: "phép chẩn đoán, triệu chứng" },
        { en: "diagram", vi: "biểu đồ" },
        { en: "diamond", vi: "kim cương" },
        { en: "disable", vi: "vô hiệu hóa, làm mất khả năng hoạt động" },
        { en: "disgust", vi: "sự kinh tởm, chán ghét" },
        { en: "donut", vi: "bánh vòng" },
        { en: "doorman", vi: "người gác cửa" },
        { en: "electronically", vi: "được xử lý bằng điện tử" },
        { en: "elevate", vi: "nâng cao" },
        { en: "engagement", vi: "sự tham gia" },
        { en: "enrollment", vi: "sự kết nạp, sự ghi danh" },
        { en: "euro", vi: "một đơn vị tiền được sử dụng ở một số quốc gia châu Âu" },
        { en: "forbid", vi: "ngăn cấm" },
        { en: "fork", vi: "cái nĩa" },
        { en: "foster", vi: "khuyến khích, cổ vũ" },
        { en: "getaway", vi: "sự chạy trốn, sự trốn thoát" },
        { en: "gossip", vi: "ngồi lê đôi mách, bàn tán sau lưng" },
        { en: "hacker", vi: "người lấy dữ liệu máy tính mà không được phép, tin tặc" },
        { en: "hardworking", vi: "làm việc chăm chỉ" },
        { en: "impatient", vi: "thiếu kiên nhẫn, nóng vội" },
        { en: "indirect", vi: "gián tiếp" },
        { en: "interpreter", vi: "người phiên dịch, phiên dịch viên" },
        { en: "intersection", vi: "ngã tư đường" },
        { en: "irrelevant", vi: "không liên quan đến chủ đề, không quan trọng" },
        { en: "jeans", vi: "quần bò" },
        { en: "journalism", vi: "nghề làm báo, ngành báo chí" },
        { en: "letterhead", vi: "phần tiêu đề trên giấy viết thư, bao gồm tên và địa chỉ" },
        { en: "volleyball", vi: "bóng chuyền" },
        { en: "wheelchair", vi: "xe lăn" },
        { en: "whoever", vi: "bất cứ ai" },
        { en: "wool", vi: "lông cừu" },
        { en: "wrinkle", vi: "nếp nhăn, nếp gấp" },

        // ==================== LIST 22 ====================
        { en: "abide", vi: "chịu đựng" },
        { en: "actively", vi: "một cách tích cực" },
        { en: "allergy", vi: "dị ứng" },
        { en: "apprehensive", vi: "không thoải mái, lo lắng" },
        { en: "automotive", vi: "thuộc hoặc liên quan đến xe cơ giới" },
        { en: "bacteria", vi: "vi khuẩn" },
        { en: "broaden", vi: "mở rộng" },
        { en: "bulb", vi: "hình dạng của một giọt nước, một vật, bóng đèn" },
        { en: "by-law", vi: "một quy tắc được đưa ra bởi một công ty hoặc xã hội để kiểm soát hành động của các thành viên" },
        { en: "lifeguard", vi: "người cứu hộ" },
        { en: "modem", vi: "mô-đem, một loại thiết bị ngoại vi của máy tính" },
        { en: "monument", vi: "đài tưởng niệm" },
        { en: "mosquito", vi: "muỗi" },
        { en: "obligate", vi: "bắt buộc, ép buộc" },
        { en: "oblige", vi: "làm cho ai phải tuân theo" },
        { en: "occurrence", vi: "sự kiện, chuyện xảy ra" },
        { en: "operational", vi: "thuộc quá trình hoạt động" },
        { en: "outage", vi: "sự ngừng chạy của máy, thiết bị hoặc thiết bị điện" },
        { en: "overcrowd", vi: "đám đông, kéo vào quá đông" },
        { en: "paralegal", vi: "trợ lý luật sư" },
        { en: "partially", vi: "một phần" },
        { en: "pepper", vi: "hạt tiêu" },
        { en: "permanently", vi: "vĩnh viễn" },
        { en: "plow", vi: "buộc phải vượt qua một trở ngại nào đó" },
        { en: "query", vi: "hỏi" },
        { en: "railway", vi: "vận tải đường sắt" },
        { en: "raincoat", vi: "áo mưa" },
        { en: "reconsider", vi: "cân nhắc lại" },
        { en: "redesign", vi: "thiết kế lại hoặc tái thiết kế" },
        { en: "rehearsal", vi: "buổi diễn tập" },
        { en: "relaxation", vi: "sự nghỉ ngơi, thư giãn" },
        { en: "repetition", vi: "sự nhắc lại, sự lặp lại" },
        { en: "retreat", vi: "rút lui, lùi về" },
        { en: "salon", vi: "thẩm mỹ viện" },
        { en: "satellite office", vi: "một chi nhánh khác của một văn phòng" },
        { en: "scenery", vi: "phong cảnh" },
        { en: "serial", vi: "liên tục, nối tiếp" },
        { en: "sew", vi: "may vá" },
        { en: "sketch", vi: "bản phác thảo" },
        { en: "soar", vi: "bay lên" },
        { en: "stimulus", vi: "tác nhân kích thích" },
        { en: "stockbroker", vi: "người môi giới chứng khoán" },
        { en: "tablecloth", vi: "khăn trải bàn" },
        { en: "thirsty", vi: "khát nước" },
        { en: "thrill", vi: "sự phấn khích" },
        { en: "tile", vi: "ngói, đá lát dùng để che mái nhà, tường hoặc sàn" },
        { en: "toiletry", vi: "các vật dụng dùng khi tắm rửa" },
        { en: "trademark", vi: "nhãn hiệu" },
        { en: "tropical", vi: "nhiệt đới" },
        { en: "tuna", vi: "cá ngừ" },
        { en: "unemployed", vi: "không có việc làm" },
        { en: "validate", vi: "công nhận có giá trị, làm cho logic, làm cho hợp lý" },
        { en: "vanilla", vi: "hương vị vani" },
        { en: "willingness", vi: "sự sẵn lòng" },
        { en: "wristwatch", vi: "đồng hồ đeo tay" },

        // ==================== LIST 23 ====================
        { en: "acclaim", vi: "sự chấp thuận và khen ngợi" },
        { en: "bookcase", vi: "tủ sách, kệ sách" },
        { en: "cheer", vi: "cổ vũ, hoan hô" },
        { en: "chronic", vi: "trong một khoảng thời gian dài" },
        { en: "cleanliness", vi: "trạng thái không bẩn, sạch sẽ" },
        { en: "complication", vi: "sự phức tạp, sự rắc rối" },
        { en: "considerate", vi: "ân cần, chu đáo, hay quan tâm tới người khác" },
        { en: "contestant", vi: "thí sinh, người dự thi" },
        { en: "daytime", vi: "ban ngày" },
        { en: "decoration", vi: "hành động trang trí một cái gì đó để làm cho hấp dẫn hơn" },
        { en: "deteriorate", vi: "trở nên tồi tệ hơn, xấu đi" },
        { en: "discard", vi: "vứt bỏ" },
        { en: "drastically", vi: "một cách trầm trọng, mãnh liệt" },
        { en: "erase", vi: "xóa bỏ" },
        { en: "ethics", vi: "đạo đức, luân thường đạo lý" },
        { en: "explorer", vi: "nhà thám hiểm" },
        { en: "factual", vi: "căn cứ theo sự thực" },
        { en: "fixture", vi: "vật cố định, đồ đặc biệt cố định" },
        { en: "footwear", vi: "giày dép" },
        { en: "genre", vi: "thể loại" },
        { en: "gymnasium", vi: "nhà thể dục" },
        { en: "healthful", vi: "lành mạnh, có lợi cho sức khỏe" },
        { en: "hereby", vi: "bằng cách này, nhờ đó" },
        { en: "hesitation", vi: "sự do dự" },
        { en: "homemade", vi: "không mua từ một cửa hàng, làm ở nhà" },
        { en: "hospitality", vi: "sự hiếu khách, thân thiện" },
        { en: "incoming", vi: "mới đến, sắp tới" },
        { en: "induction", vi: "sự giới thiệu vào một tổ chức" },
        { en: "inefficient", vi: "không hoạt động tốt hoặc thành công" },
        { en: "inspiration", vi: "nguồn cảm hứng" },
        { en: "intently", vi: "chăm chú" },
        { en: "liter", vi: "lít, một đơn vị đo lường cho chất lỏng" },
        { en: "mower", vi: "máy dùng để cắt cỏ" },
        { en: "nutrition", vi: "khoa dinh dưỡng" },
        { en: "recession", vi: "sự suy thoái" },
        { en: "resemble", vi: "trông giống nhau, tương tự nhau" },
        { en: "restatement", vi: "sự trình bày, sự nói lại" },
        { en: "sedan", vi: "loại xe 4 cửa, có 4 chỗ ngồi" },
        { en: "sunscreen", vi: "kem chống nắng" },
        { en: "timeline", vi: "một chuỗi các sự kiện theo dòng thời gian" },
        { en: "unauthorize", vi: "từ chối thẩm quyền, không cho phép" },
        { en: "unplug", vi: "rút dây điện ra khỏi ổ cắm" },
        { en: "unreliable", vi: "không đáng tin cậy" },
        { en: "video conference", vi: "cuộc họp được thực hiện qua internet" },
        { en: "violate", vi: "vi phạm quy tắc hoặc luật pháp" },
        { en: "wellness", vi: "trạng thái khỏe mạnh, không bị bệnh" },
        { en: "workbook", vi: "sách bài tập" }
    ];

    /* =====================================================
       FLASHCARD ANH → VIỆT
    ===================================================== */

    window.medQuizFlashcards["Tiếng Anh"] = vocabulary.map((item, index) => ({
        id: `english2-${String(index + 1).padStart(3, "0")}`,
        front: item.en,
        back: item.vi,
        pronunciation: "",
        example: ""
    }));

    /* =====================================================
       TRẮC NGHIỆM ANH → VIỆT
       Mỗi câu có 4 đáp án.
    ===================================================== */

    function shuffle(array) {
        const result = [...array];

        for (let i = result.length - 1; i > 0; i--) {
            const j = Math.floor(Math.random() * (i + 1));
            [result[i], result[j]] = [result[j], result[i]];
        }

        return result;
    }

    function unique(array) {
        return [...new Set(array)];
    }

    const vietnamesePool = unique(vocabulary.map(item => item.vi));

    window.medQuizQuestions["Tiếng Anh"] = vocabulary.map((item, index) => {
        const wrongAnswers = shuffle(
            vietnamesePool.filter(answer => answer !== item.vi)
        ).slice(0, 3);

        const answers = shuffle([
            item.vi,
            ...wrongAnswers
        ]);

        return {
            id: `english2-quiz-${index + 1}`,
            question: `Từ “${item.en}” có nghĩa là gì?`,
            answers: answers,
            correct: answers.indexOf(item.vi),
            explanation: `✅ ${item.en} = ${item.vi}`
        };
    });

    console.log(
        `✅ tienganh2.js: ${vocabulary.length} từ | ` +
        `${window.medQuizQuestions["Tiếng Anh"].length} câu trắc nghiệm Anh → Việt`
    );
})();
