"use strict";

/* Tiếng Anh — dữ liệu riêng cho Luyện từ. Đồng bộ 55 từ với Flashcard. */
(function(){
  window.medQuizWordPractice = window.medQuizWordPractice || {};
  window.medQuizWordPractice["Tiếng Anh"] = [
    {"id": "english-word-001", "front": "accountant", "back": "một người chịu trách nhiệm về tiền trong một doanh nghiệp; kế toán", "pronunciation": "", "example": ""},
    {"id": "english-word-002", "front": "airport", "back": "sân bay", "pronunciation": "", "example": ""},
    {"id": "english-word-003", "front": "applicant", "back": "ứng viên", "pronunciation": "", "example": ""},
    {"id": "english-word-004", "front": "attendant", "back": "người phục vụ", "pronunciation": "", "example": ""},
    {"id": "english-word-005", "front": "bicycle", "back": "xe đạp", "pronunciation": "", "example": ""},
    {"id": "english-word-006", "front": "brochure", "back": "tờ gấp quảng cáo", "pronunciation": "", "example": ""},
    {"id": "english-word-007", "front": "cafeteria", "back": "quán ăn tự phục vụ", "pronunciation": "", "example": ""},
    {"id": "english-word-008", "front": "caller", "back": "người đang gọi điện cho bạn", "pronunciation": "", "example": ""},
    {"id": "english-word-009", "front": "candidate", "back": "ứng cử viên", "pronunciation": "", "example": ""},
    {"id": "english-word-010", "front": "chef", "back": "đầu bếp", "pronunciation": "", "example": ""},
    {"id": "english-word-011", "front": "clerk", "back": "nhân viên bán hàng", "pronunciation": "", "example": ""},
    {"id": "english-word-012", "front": "client", "back": "khách hàng", "pronunciation": "", "example": ""},
    {"id": "english-word-013", "front": "cloth", "back": "cái khăn", "pronunciation": "", "example": ""},
    {"id": "english-word-014", "front": "conference", "back": "hội nghị; hội thảo", "pronunciation": "", "example": ""},
    {"id": "english-word-015", "front": "correctly", "back": "một cách chính xác; đúng đắn", "pronunciation": "", "example": ""},
    {"id": "english-word-016", "front": "deadline", "back": "hạn chót; thời gian cụ thể hoàn thành một nhiệm vụ hoặc công việc được giao", "pronunciation": "", "example": ""},
    {"id": "english-word-017", "front": "downtown", "back": "khu vực trung tâm của thành phố", "pronunciation": "", "example": ""},
    {"id": "english-word-018", "front": "e-book", "back": "sách điện tử", "pronunciation": "", "example": ""},
    {"id": "english-word-019", "front": "elevator", "back": "thang máy", "pronunciation": "", "example": ""},
    {"id": "english-word-020", "front": "enclose", "back": "vây quanh; rào quanh", "pronunciation": "", "example": ""},
    {"id": "english-word-021", "front": "fare", "back": "tiền xe; tiền vé", "pronunciation": "", "example": ""},
    {"id": "english-word-022", "front": "fax", "back": "gửi bằng máy fax", "pronunciation": "", "example": ""},
    {"id": "english-word-023", "front": "goods", "back": "hàng hóa; mặt hàng", "pronunciation": "", "example": ""},
    {"id": "english-word-024", "front": "infer", "back": "suy ra; phỏng đoán", "pronunciation": "", "example": ""},
    {"id": "english-word-025", "front": "invoice", "back": "hóa đơn", "pronunciation": "", "example": ""},
    {"id": "english-word-026", "front": "lease", "back": "thuê", "pronunciation": "", "example": ""},
    {"id": "english-word-027", "front": "lobby", "back": "tiền sảnh của khách sạn", "pronunciation": "", "example": ""},
    {"id": "english-word-028", "front": "logical", "back": "theo logic; hợp lý", "pronunciation": "", "example": ""},
    {"id": "english-word-029", "front": "luggage", "back": "hành lý", "pronunciation": "", "example": ""},
    {"id": "english-word-030", "front": "memo", "back": "giấy ghi chú", "pronunciation": "", "example": ""},
    {"id": "english-word-031", "front": "mister", "back": "một cách xưng hô lịch sự với một người đàn ông", "pronunciation": "", "example": ""},
    {"id": "english-word-032", "front": "noon", "back": "giữa trưa", "pronunciation": "", "example": ""},
    {"id": "english-word-033", "front": "notify", "back": "thông báo; cho biết", "pronunciation": "", "example": ""},
    {"id": "english-word-034", "front": "o'clock", "back": "giờ trong ngày", "pronunciation": "", "example": ""},
    {"id": "english-word-035", "front": "preview", "back": "sự xem trước; sự duyệt trước", "pronunciation": "", "example": ""},
    {"id": "english-word-036", "front": "publish", "back": "xuất bản; công bố; đăng tải", "pronunciation": "", "example": ""},
    {"id": "english-word-037", "front": "receipt", "back": "hóa đơn", "pronunciation": "", "example": ""},
    {"id": "english-word-038", "front": "reception", "back": "sự đón tiếp; tiệc chiêu đãi", "pronunciation": "", "example": ""},
    {"id": "english-word-039", "front": "refund", "back": "hoàn tiền", "pronunciation": "", "example": ""},
    {"id": "english-word-040", "front": "rental", "back": "sự cho thuê", "pronunciation": "", "example": ""},
    {"id": "english-word-041", "front": "reservation", "back": "sự đặt trước", "pronunciation": "", "example": ""},
    {"id": "english-word-042", "front": "seminar", "back": "buổi hội thảo; nghiên cứu khoa học; nghiên cứu chuyên đề; buổi báo cáo công việc", "pronunciation": "", "example": ""},
    {"id": "english-word-043", "front": "shipment", "back": "sự giao hàng", "pronunciation": "", "example": ""},
    {"id": "english-word-044", "front": "sincerely", "back": "một cách chân thành", "pronunciation": "", "example": ""},
    {"id": "english-word-045", "front": "sometime", "back": "một lúc nào đó", "pronunciation": "", "example": ""},
    {"id": "english-word-046", "front": "subscription", "back": "sự đăng ký", "pronunciation": "", "example": ""},
    {"id": "english-word-047", "front": "subway", "back": "đường hầm", "pronunciation": "", "example": ""},
    {"id": "english-word-048", "front": "supervisor", "back": "người giám sát", "pronunciation": "", "example": ""},
    {"id": "english-word-049", "front": "technician", "back": "kỹ thuật viên", "pronunciation": "", "example": ""},
    {"id": "english-word-050", "front": "traveler", "back": "khách du lịch", "pronunciation": "", "example": ""},
    {"id": "english-word-051", "front": "vacation", "back": "kỳ nghỉ", "pronunciation": "", "example": ""},
    {"id": "english-word-052", "front": "waiter", "back": "nhân viên phục vụ nam", "pronunciation": "", "example": ""},
    {"id": "english-word-053", "front": "warranty", "back": "sự bảo hành", "pronunciation": "", "example": ""},
    {"id": "english-word-054", "front": "website", "back": "trang web", "pronunciation": "", "example": ""},
    {"id": "english-word-055", "front": "workshop", "back": "phân xưởng", "pronunciation": "", "example": ""}
  ];
})();
