"use strict";

/* =========================================================
   TIẾNG ANH 11 - flashcards/tienganh11.js

   ĐÃ GHÉP LIST 1 → LIST 10

   Chức năng:
   Dữ liệu riêng cho mục LUYỆN TỪ.
   Hỗ trợ cả 2 chiều:
   - Anh → Việt
   - Việt → Anh

   Main script của website sẽ tự chọn chiều luyện từ.

   Tổng: 550 từ
========================================================= */

(function () {
    window.medQuizFlashcards = window.medQuizFlashcards || {};

    const vocabulary = [
        // ==================== LIST 1 ====================
        { en: "accountant", vi: "một người chịu trách nhiệm về tiền trong một doanh nghiệp; kế toán" },
        { en: "airport", vi: "sân bay" },
        { en: "applicant", vi: "ứng viên" },
        { en: "attendant", vi: "người phục vụ" },
        { en: "bicycle", vi: "xe đạp" },
        { en: "brochure", vi: "tờ gấp quảng cáo" },
        { en: "cafeteria", vi: "quán ăn tự phục vụ" },
        { en: "caller", vi: "người đang gọi điện cho bạn" },
        { en: "candidate", vi: "ứng cử viên" },
        { en: "chef", vi: "đầu bếp" },
        { en: "clerk", vi: "nhân viên bán hàng" },
        { en: "client", vi: "khách hàng" },
        { en: "cloth", vi: "cái khăn" },
        { en: "conference", vi: "hội nghị; hội thảo" },
        { en: "correctly", vi: "một cách chính xác; đúng đắn" },
        { en: "deadline", vi: "hạn chót; thời gian cụ thể hoàn thành một nhiệm vụ hoặc công việc được giao" },
        { en: "downtown", vi: "khu vực trung tâm của thành phố" },
        { en: "e-book", vi: "sách điện tử" },
        { en: "elevator", vi: "thang máy" },
        { en: "enclose", vi: "vây quanh; rào quanh" },
        { en: "fare", vi: "tiền xe; tiền vé" },
        { en: "fax", vi: "gửi bằng máy fax" },
        { en: "goods", vi: "hàng hóa; mặt hàng" },
        { en: "infer", vi: "suy ra; phỏng đoán" },
        { en: "invoice", vi: "hóa đơn" },
        { en: "lease", vi: "thuê" },
        { en: "lobby", vi: "tiền sảnh của khách sạn" },
        { en: "logical", vi: "theo logic; hợp lý" },
        { en: "luggage", vi: "hành lý" },
        { en: "memo", vi: "giấy ghi chú" },
        { en: "mister", vi: "một cách xưng hô lịch sự với một người đàn ông" },
        { en: "noon", vi: "giữa trưa" },
        { en: "notify", vi: "thông báo; cho biết" },
        { en: "o'clock", vi: "giờ trong ngày" },
        { en: "preview", vi: "sự xem trước; sự duyệt trước" },
        { en: "publish", vi: "xuất bản; công bố; đăng tải" },
        { en: "receipt", vi: "hóa đơn" },
        { en: "reception", vi: "sự đón tiếp; tiệc chiêu đãi" },
        { en: "refund", vi: "hoàn tiền" },
        { en: "rental", vi: "sự cho thuê" },
        { en: "reservation", vi: "sự đặt trước" },
        { en: "seminar", vi: "buổi hội thảo; nghiên cứu khoa học; nghiên cứu chuyên đề; buổi báo cáo công việc" },
        { en: "shipment", vi: "sự giao hàng" },
        { en: "sincerely", vi: "một cách chân thành" },
        { en: "sometime", vi: "một lúc nào đó" },
        { en: "subscription", vi: "sự đăng ký" },
        { en: "subway", vi: "đường hầm" },
        { en: "supervisor", vi: "người giám sát" },
        { en: "technician", vi: "kỹ thuật viên" },
        { en: "traveler", vi: "khách du lịch" },
        { en: "vacation", vi: "kỳ nghỉ" },
        { en: "waiter", vi: "nhân viên phục vụ nam" },
        { en: "warranty", vi: "sự bảo hành" },
        { en: "website", vi: "trang web" },
        { en: "workshop", vi: "phân xưởng" },

        // ==================== LIST 2 ====================
        { en: "admission", vi: "sự nhận vào, sự thu nạp; sự thú nhận" },
        { en: "airplane", vi: "máy bay" },
        { en: "appliance", vi: "máy móc, thiết bị" },
        { en: "assignment", vi: "một dự án hoặc nhiệm vụ" },
        { en: "attendee", vi: "người tham gia, người tham dự" },
        { en: "birthday", vi: "sinh nhật" },
        { en: "cabinet", vi: "tủ có nhiều ngăn" },
        { en: "café", vi: "quán cà phê" },
        { en: "cellphone", vi: "điện thoại di động" },
        { en: "clue", vi: "gợi ý, manh mối" },
        { en: "compact", vi: "gọn ghẽ/chật ních" },
        { en: "comprehension", vi: "sự hiểu, sự lĩnh hội" },
        { en: "contradict", vi: "phủ nhận/mâu thuẫn" },
        { en: "convenient", vi: "tiện lợi, thuận tiện" },
        { en: "coupon", vi: "phiếu mua hàng, phiếu giảm giá" },
        { en: "coworker", vi: "đồng nghiệp" },
        { en: "cruise", vi: "cuộc du ngoạn biển bằng tàu" },
        { en: "dentist", vi: "bác sĩ nha khoa" },
        { en: "depart", vi: "rời đi, khởi hành" },
        { en: "destination", vi: "điểm đến" },
        { en: "dine", vi: "ăn tối" },
        { en: "electrical", vi: "thuộc về điện" },
        { en: "exit", vi: "rời đi" },
        { en: "explanatory", vi: "để giải thích hoặc làm rõ" },
        { en: "garage", vi: "nhà xe, ga-ra xe" },
        { en: "identification", vi: "giấy tờ nhận dạng" },
        { en: "inference", vi: "kết luận, sự suy luận" },
        { en: "instructor", vi: "người hướng dẫn (có thể là huấn luyện viên, giáo viên)" },
        { en: "inventory", vi: "bản kiểm kê" },
        { en: "keyboard", vi: "bàn phím máy tính" },
        { en: "laptop", vi: "máy tính xách tay" },
        { en: "mall", vi: "trung tâm thương mại, trung tâm mua sắm" },
        { en: "manual", vi: "sách hướng dẫn" },
        { en: "media", vi: "phương tiện truyền thông đại chúng" },
        { en: "medication", vi: "thuốc thang, dược phẩm" },
        { en: "merchandise", vi: "hàng hóa" },
        { en: "obtain", vi: "đạt được, có được" },
        { en: "occupation", vi: "nghề nghiệp" },
        { en: "outdoor", vi: "ngoài trời" },
        { en: "oval", vi: "hình trái xoan, hình bầu dục" },
        { en: "passport", vi: "hộ chiếu" },
        { en: "postpone", vi: "trì hoãn, hoãn lại" },
        { en: "precede", vi: "ở trước, có trước, đến trước" },
        { en: "receptionist", vi: "nhân viên tiếp tân" },
        { en: "renovation", vi: "sự nâng cấp, sự tu sửa" },
        { en: "replacement", vi: "sự thay thế, vật thay thế, người thay thế" },
        { en: "reschedule", vi: "xếp lại lịch" },
        { en: "suitcase", vi: "vali" },
        { en: "supermarket", vi: "siêu thị" },
        { en: "tactic", vi: "chiến thuật" },
        { en: "umbrella", vi: "tổ chức bảo trợ, thế lực bảo vệ, sự bao trùm" },
        { en: "underline", vi: "nhấn mạnh/gạch chân" },
        { en: "upcoming", vi: "sắp tới" },
        { en: "upgrade", vi: "nâng cấp" },
        { en: "valid", vi: "đúng đắn, có cơ sở/căn cứ vững chắc" },

        // ==================== LIST 3 ====================
        { en: "aisle", vi: "lối đi hẹp" },
        { en: "architect", vi: "kiến trúc sư" },
        { en: "baggage", vi: "hành lý" },
        { en: "banquet", vi: "yến tiệc, đại tiệc" },
        { en: "beverage", vi: "đồ uống" },
        { en: "bulletin", vi: "bản tin, thông báo" },
        { en: "calendar", vi: "lịch" },
        { en: "certificate", vi: "giấy chứng nhận, chứng chỉ" },
        { en: "click", vi: "nhấn nút" },
        { en: "closet", vi: "tủ/phòng để đồ" },
        { en: "container", vi: "vật chứa, vật đựng" },
        { en: "convenience", vi: "sự tiện lợi, sự thuận lợi" },
        { en: "copier", vi: "máy photocopy" },
        { en: "departure", vi: "sự khởi hành" },
        { en: "dial", vi: "bấm số điện thoại" },
        { en: "distractor", vi: "thông tin gây nhiễu, lựa chọn gây nhiễu" },
        { en: "donation", vi: "đồ quyên góp, khoản tiền quyên góp" },
        { en: "drawer", vi: "ngăn kéo" },
        { en: "eligible", vi: "đủ điều kiện, đủ tư cách, thích hợp" },
        { en: "expire", vi: "hết hạn, kết thúc" },
        { en: "feedback", vi: "ý kiến phản hồi" },
        { en: "fitness", vi: "trạng thái khỏe mạnh" },
        { en: "folder", vi: "thư mục, bìa đựng hồ sơ" },
        { en: "gym", vi: "phòng thể dục, phòng tập thể hình" },
        { en: "highway", vi: "đường cao tốc, quốc lộ" },
        { en: "hungry", vi: "đói bụng" },
        { en: "inconvenience", vi: "sự bất tiện" },
        { en: "indoor", vi: "trong nhà" },
        { en: "ingredient", vi: "nguyên liệu" },
        { en: "inspect", vi: "kiểm tra" },
        { en: "inspection", vi: "sự kiểm tra, sự thanh tra" },
        { en: "itinerary", vi: "lộ trình" },
        { en: "lab", vi: "phòng thí nghiệm" },
        { en: "mechanic", vi: "thợ máy" },
        { en: "merger", vi: "sự sáp nhập" },
        { en: "mini", vi: "nhỏ hơn bình thường" },
        { en: "photocopy", vi: "bản sao" },
        { en: "provider", vi: "người cung cấp, nhà cung cấp" },
        { en: "recipient", vi: "người nhận" },
        { en: "recycle", vi: "tái chế" },
        { en: "renew", vi: "thay mới, làm mới lại" },
        { en: "renovate", vi: "nâng cấp, cải tiến, tân trang" },
        { en: "respondent", vi: "người trả lời, người được hỏi" },
        { en: "rewrite", vi: "viết lại" },
        { en: "sandwich", vi: "bánh mì sandwich" },
        { en: "shortly", vi: "trong thời gian ngắn, không lâu, sớm" },
        { en: "snack", vi: "đồ ăn nhẹ" },
        { en: "soccer", vi: "bóng đá" },
        { en: "submission", vi: "sự đệ trình, sự nộp lên" },
        { en: "sunny", vi: "nhiều nắng" },
        { en: "sweater", vi: "áo len chui đầu" },
        { en: "tenant", vi: "người thuê (nhà, phòng...)" },
        { en: "unreal", vi: "không thực tế" },
        { en: "warehouse", vi: "nhà kho" },
        { en: "workplace", vi: "chỗ làm, nơi làm việc" },

        // ==================== LIST 4 ====================
        { en: "accommodate", vi: "cung cấp một cái gì đó cần thiết" },
        { en: "administrative", vi: "thuộc về hành chính, quản lý văn phòng" },
        { en: "advisor", vi: "cố vấn" },
        { en: "alike", vi: "tương tự, gần như giống nhau" },
        { en: "announcer", vi: "người báo tin, phát thanh viên" },
        { en: "aspect", vi: "khía cạnh, điểm đặc trưng" },
        { en: "audit", vi: "kiểm toán, kiểm tra sổ sách" },
        { en: "authorize", vi: "cho phép, ủy quyền" },
        { en: "battery", vi: "pin" },
        { en: "bonus", vi: "tiền thưởng thêm" },
        { en: "briefcase", vi: "cặp đựng tài liệu" },
        { en: "cart", vi: "xe kéo, xe đẩy" },
        { en: "cartridge", vi: "hộp chứa, hộp đựng của thiết bị có thể tháo lắp và thay thế" },
        { en: "cleaner", vi: "người dọn dẹp" },
        { en: "cloudy", vi: "nhiều mây" },
        { en: "commonly", vi: "thông thường, thường xuyên" },
        { en: "commuter", vi: "người đi làm" },
        { en: "contractor", vi: "nhà thầu, bên thi công" },
        { en: "delicious", vi: "ngon miệng" },
        { en: "dessert", vi: "món tráng miệng" },
        { en: "developer", vi: "chủ xây dựng nhà cửa, người kinh doanh nhà đất" },
        { en: "distribution", vi: "sự phân bố, sự phân phối" },
        { en: "donate", vi: "quyên góp" },
        { en: "download", vi: "tải xuống" },
        { en: "flavor", vi: "hương vị" },
        { en: "headquarter", vi: "trụ sở chính, tổng bộ" },
        { en: "impact", vi: "sự tác động, sự ảnh hưởng" },
        { en: "ink", vi: "mực" },
        { en: "innovative", vi: "có tính sáng tạo và đổi mới" },
        { en: "inquire", vi: "hỏi (về cái gì/vấn đề gì)" },
        { en: "jewelry", vi: "đồ trang sức" },
        { en: "logo", vi: "biểu tượng" },
        { en: "newsletter", vi: "thư báo cáo hoặc thư thông báo" },
        { en: "outstanding", vi: "chưa giải quyết" },
        { en: "overnight", vi: "qua đêm" },
        { en: "overtime", vi: "giờ làm thêm" },
        { en: "password", vi: "mật khẩu" },
        { en: "photographer", vi: "nhiếp ảnh gia, thợ chụp ảnh" },
        { en: "picnic", vi: "bữa ăn ngoài trời" },
        { en: "prohibit", vi: "không cho phép" },
        { en: "recipe", vi: "công thức" },
        { en: "refreshment", vi: "món ăn nhẹ" },
        { en: "shopper", vi: "người mua hàng" },
        { en: "shuttle", vi: "đi lại giữa hai điểm" },
        { en: "skim", vi: "lướt qua" },
        { en: "sofa", vi: "ghế sô pha" },
        { en: "stadium", vi: "sân vận động" },
        { en: "stationery", vi: "văn phòng phẩm" },
        { en: "subscribe", vi: "đăng ký" },
        { en: "supervise", vi: "theo dõi, giám sát" },
        { en: "tag", vi: "nhãn dán" },
        { en: "terminal", vi: "ga chót, ga cuối cùng" },
        { en: "venue", vi: "nơi sự kiện diễn ra" },
        { en: "waitress", vi: "người phục vụ (nữ giới)" },
        { en: "weekday", vi: "ngày thường" },

        // ==================== LIST 5 ====================
        { en: "affordable", vi: "vừa túi tiền, có thể chi trả" },
        { en: "annoy", vi: "làm phiền hoặc làm khó chịu" },
        { en: "authority", vi: "thẩm quyền, uy quyền" },
        { en: "automobile", vi: "xe hơi" },
        { en: "availability", vi: "sự có sẵn, tính sẵn sàng để dùng" },
        { en: "bargain", vi: "món hời, mức giá tốt" },
        { en: "baseball", vi: "môn bóng chày" },
        { en: "bookstore", vi: "hiệu sách" },
        { en: "captain", vi: "thuyền trưởng, cơ trưởng" },
        { en: "carrier", vi: "người chuyên chở, phương tiện chuyên chở" },
        { en: "cater", vi: "cung cấp, phục vụ thực phẩm" },
        { en: "commute", vi: "đi lại đến chỗ làm việc" },
        { en: "complimentary", vi: "không tốn gì, miễn phí" },
        { en: "coordinate", vi: "điều phối, phối hợp, tổ chức" },
        { en: "courier", vi: "người đưa thư, chuyển phát nhanh" },
        { en: "dental", vi: "liên quan đến răng" },
        { en: "designate", vi: "chỉ định" },
        { en: "dock", vi: "bến tàu thủy" },
        { en: "duration", vi: "khoảng thời gian, độ lâu" },
        { en: "exclusive", vi: "dành riêng, độc quyền" },
        { en: "flu", vi: "bệnh cúm" },
        { en: "grocery", vi: "cửa hàng tạp hóa" },
        { en: "hike", vi: "đi bộ đường dài" },
        { en: "homework", vi: "bài tập về nhà" },
        { en: "incomplete", vi: "chưa hoàn thành" },
        { en: "installation", vi: "sự lắp đặt" },
        { en: "lamp", vi: "đèn" },
        { en: "lately", vi: "mới đây" },
        { en: "lounge", vi: "phòng khách, phòng ngồi chơi (ở khách sạn)" },
        { en: "machinery", vi: "máy móc, thiết bị" },
        { en: "memorandum", vi: "bản ghi nhớ" },
        { en: "midnight", vi: "nửa đêm" },
        { en: "painter", vi: "họa sĩ" },
        { en: "paperwork", vi: "công việc giấy tờ" },
        { en: "patron", vi: "người bảo trợ" },
        { en: "photocopier", vi: "máy photocopy" },
        { en: "prescription", vi: "đơn thuốc" },
        { en: "presenter", vi: "người dẫn chương trình, xướng ngôn viên" },
        { en: "productive", vi: "có hiệu quả" },
        { en: "productivity", vi: "năng suất công việc" },
        { en: "questionnaire", vi: "bộ câu hỏi" },
        { en: "quit", vi: "bỏ, dừng" },
        { en: "rainy", vi: "có mưa, nhiều mưa" },
        { en: "relocate", vi: "di dời đến một địa điểm mới" },
        { en: "salad", vi: "món salad" },
        { en: "seldom", vi: "hiếm khi" },
        { en: "signature", vi: "chữ ký" },
        { en: "suite", vi: "dãy phòng" },
        { en: "thorough", vi: "kỹ lưỡng, thấu đáo" },
        { en: "trainee", vi: "học viên, thực tập sinh" },
        { en: "trainer", vi: "người huấn luyện/huấn luyện viên" },
        { en: "transaction", vi: "sự buôn bán; sự giao dịch" },
        { en: "unhappy", vi: "không hạnh phúc, không vui" },
        { en: "verify", vi: "xác minh, kiểm tra" },
        { en: "worldwide", vi: "toàn cầu, khắp thế giới" },

        // ==================== LIST 6 ====================
        { en: "accurately", vi: "một cách đúng đắn, chính xác" },
        { en: "anniversary", vi: "ngày kỷ niệm" },
        { en: "annually", vi: "hàng năm, mỗi 12 tháng" },
        { en: "banker", vi: "người làm trong lĩnh vực ngân hàng" },
        { en: "basketball", vi: "môn bóng rổ" },
        { en: "bathroom", vi: "nhà vệ sinh, nhà tắm" },
        { en: "behalf", vi: "thay mặt, nhân danh" },
        { en: "buffet", vi: "tiệc đứng tự phục vụ" },
        { en: "cab", vi: "xe tắc xi" },
        { en: "cabin", vi: "nhà gỗ nhỏ trong rừng" },
        { en: "calculator", vi: "máy tính cầm tay" },
        { en: "completion", vi: "kết thúc, sự hoàn thành" },
        { en: "conductor", vi: "người chỉ huy, người chỉ đạo" },
        { en: "confirmation", vi: "sự xác nhận, sự xác minh" },
        { en: "congratulation", vi: "lời chúc mừng, việc chúc mừng" },
        { en: "correspondence", vi: "giao tiếp bằng thư" },
        { en: "defect", vi: "lỗi, thiếu sót, sai sót" },
        { en: "defective", vi: "có thiếu sót, bị lỗi" },
        { en: "delegate", vi: "ủy nhiệm, giao nhiệm vụ" },
        { en: "delete", vi: "xóa" },
        { en: "expertise", vi: "sự thành thạo, kỹ năng chuyên môn" },
        { en: "garbage", vi: "rác; thứ vô giá trị" },
        { en: "graph", vi: "đồ thị, biểu đồ" },
        { en: "ice cream", vi: "kem" },
        { en: "illogical", vi: "phi logic, vô lý" },
        { en: "inspector", vi: "sĩ quan cảnh sát cấp cao, thanh tra cảnh sát" },
        { en: "intern", vi: "thực tập sinh" },
        { en: "ladder", vi: "thang" },
        { en: "leak", vi: "rò rỉ" },
        { en: "minimize", vi: "giảm thiểu, thu nhỏ" },
        { en: "occupancy", vi: "sự lưu trú" },
        { en: "omit", vi: "bỏ qua hoặc không đề cập đến" },
        { en: "optional", vi: "tùy ý, không bắt buộc" },
        { en: "paycheck", vi: "tiền lương" },
        { en: "pet", vi: "vật nuôi" },
        { en: "photography", vi: "nghệ thuật chụp ảnh" },
        { en: "polite", vi: "lịch sự" },
        { en: "proficiency", vi: "sự thông thạo" },
        { en: "protective", vi: "phòng ngừa, bảo hộ" },
        { en: "renewal", vi: "sự thay mới, sự đổi mới" },
        { en: "salesperson", vi: "nhân viên bán hàng" },
        { en: "sculpture", vi: "tác phẩm điêu khắc" },
        { en: "seller", vi: "người bán" },
        { en: "semester", vi: "học kỳ" },
        { en: "sidewalk", vi: "vỉa hè" },
        { en: "sightsee", vi: "đi tham quan" },
        { en: "soup", vi: "súp; canh" },
        { en: "spite", vi: "sự thù oán, sự thù hận" },
        { en: "stack", vi: "chồng, đống" },
        { en: "taker", vi: "người nhận" },
        { en: "textbook", vi: "sách giáo khoa" },
        { en: "transit", vi: "sự di chuyển" },
        { en: "urgent", vi: "cấp thiết" },
        { en: "utility", vi: "sự hữu ích" },
        { en: "voucher", vi: "phiếu giảm giá" },

        // ==================== LIST 7 ====================
        { en: "administrator", vi: "người quản lý, người cầm quyền" },
        { en: "auto", vi: "xe hơi" },
        { en: "bench", vi: "ghế dài (thường thấy trong công viên)" },
        { en: "booklet", vi: "cuốn sách nhỏ, chứa thông tin quảng cáo hoặc hướng dẫn" },
        { en: "born", vi: "sinh ra, đẻ ra" },
        { en: "broker", vi: "người môi giới" },
        { en: "cancellation", vi: "sự hủy bỏ" },
        { en: "cashier", vi: "nhân viên thu ngân" },
        { en: "casual", vi: "không thường xuyên, không có kế hoạch" },
        { en: "conditioner", vi: "dầu xả cho tóc" },
        { en: "confidential", vi: "bảo mật" },
        { en: "cumulative", vi: "tích lũy" },
        { en: "decorate", vi: "trang trí, trang hoàng" },
        { en: "deduction", vi: "sự lấy đi, sự khấu trừ" },
        { en: "definite", vi: "chắc chắn, chính xác" },
        { en: "directory", vi: "danh bạ, thư mục" },
        { en: "disposal", vi: "sự vứt bỏ đi" },
        { en: "drill", vi: "khoan lỗ" },
        { en: "economical", vi: "tiết kiệm, kinh tế" },
        { en: "efficiently", vi: "một cách hữu hiệu, một cách hiệu quả" },
        { en: "enroll", vi: "ghi danh, đăng ký" },
        { en: "flyer", vi: "tờ gấp quảng cáo, tờ rơi" },
        { en: "fountain", vi: "đài phun nước" },
        { en: "franchise", vi: "nhượng quyền kinh doanh, chi nhánh" },
        { en: "frustrate", vi: "làm thất vọng, làm bực mình" },
        { en: "garment", vi: "áo quần, hàng may mặc" },
        { en: "generous", vi: "rộng lượng, hào phóng" },
        { en: "housekeeper", vi: "người quản gia, nhân viên dọn dẹp" },
        { en: "internship", vi: "kỳ thực tập" },
        { en: "interrupt", vi: "làm gián đoạn, làm ngắt quãng" },
        { en: "juice", vi: "nước ép (từ trái cây hoặc rau củ quả)" },
        { en: "knowledgeable", vi: "am hiểu, có kiến thức" },
        { en: "lane", vi: "đường nhỏ/làn đường" },
        { en: "organizer", vi: "người tổ chức" },
        { en: "orientation", vi: "sự định hướng" },
        { en: "outlet", vi: "cửa hàng bán lẻ bán đồ xả, đồ giảm giá chính hãng" },
        { en: "oven", vi: "lò nướng" },
        { en: "overdue", vi: "quá hạn" },
        { en: "packet", vi: "thùng nhỏ, gói nhỏ, kiện hàng" },
        { en: "pant", vi: "thở hổn hển" },
        { en: "plumber", vi: "thợ sửa ống nước" },
        { en: "popularity", vi: "sự nổi tiếng, sự yêu mến của quần chúng" },
        { en: "poster", vi: "tấm áp phích quảng cáo" },
        { en: "prediction", vi: "sự phỏng đoán về tương lai" },
        { en: "profitable", vi: "có lợi nhuận" },
        { en: "promptly", vi: "nhanh chóng, ngay lập tức" },
        { en: "refrigerator", vi: "tủ lạnh" },
        { en: "reimburse", vi: "hoàn lại tiền, bồi hoàn" },
        { en: "retailer", vi: "nhà bán lẻ, cửa hàng bán lẻ" },
        { en: "showroom", vi: "nơi trưng bày, phòng trưng bày" },
        { en: "specification", vi: "chi tiết, đặc điểm, sự chỉ rõ" },
        { en: "subscriber", vi: "người đăng ký" },
        { en: "vacancy", vi: "chỗ trống, vị trí còn trống" },
        { en: "vegetarian", vi: "người ăn chay" },
        { en: "wallet", vi: "ví, bao da" },

        // ==================== LIST 8 ====================
        { en: "accessible", vi: "có sẵn, dễ dàng để tiếp cận" },
        { en: "accomplishment", vi: "sự hoàn thành, thành tựu" },
        { en: "accustom", vi: "làm quen với" },
        { en: "afterward", vi: "sau đó" },
        { en: "apology", vi: "lời xin lỗi" },
        { en: "appreciation", vi: "sự cảm kích" },
        { en: "assemble", vi: "tập hợp, tập trung" },
        { en: "automate", vi: "tự động hóa" },
        { en: "automatic", vi: "tự động" },
        { en: "cargo", vi: "hàng hóa, lô hàng chuyên chở" },
        { en: "clinic", vi: "phòng khám" },
        { en: "cooperate", vi: "hợp tác" },
        { en: "desktop", vi: "màn hình nền" },
        { en: "distract", vi: "làm xao lãng" },
        { en: "dividend", vi: "cổ tức, tiền lãi" },
        { en: "exemption", vi: "sự miễn trừ, sự ngoại lệ" },
        { en: "ferry", vi: "chiếc phà" },
        { en: "finalize", vi: "hoàn thiện" },
        { en: "furnish", vi: "trang bị đồ đạc (phòng, nhà...)" },
        { en: "hourly", vi: "mỗi giờ" },
        { en: "incur", vi: "gánh chịu, nhận lấy" },
        { en: "instruct", vi: "dạy, hướng dẫn" },
        { en: "jet", vi: "máy bay phản lực" },
        { en: "jog", vi: "chạy chậm, thong thả với tốc độ đều" },
        { en: "laundry", vi: "quần áo bẩn cần giặt" },
        { en: "leisure", vi: "thời gian rảnh, rỗi rãi" },
        { en: "loyal", vi: "trung thành, trung nghĩa" },
        { en: "luncheon", vi: "tiệc trưa" },
        { en: "mandatory", vi: "bắt buộc" },
        { en: "mechanical", vi: "thuộc máy móc; thuộc cơ khí; thuộc cơ học" },
        { en: "microphone", vi: "micrô" },
        { en: "nap", vi: "giấc ngủ trưa, chợp mắt" },
        { en: "overview", vi: "tổng quan" },
        { en: "pharmacy", vi: "nhà thuốc" },
        { en: "projector", vi: "máy chiếu" },
        { en: "promotional", vi: "quảng cáo, khuyến mãi" },
        { en: "quarterly", vi: "mỗi quý, hàng quý" },
        { en: "realistic", vi: "thực tế" },
        { en: "reinforce", vi: "củng cố, gia cố" },
        { en: "residential", vi: "thuộc nơi ở, thuộc nơi cư trú" },
        { en: "scholarship", vi: "học bổng" },
        { en: "seeker", vi: "người tìm kiếm" },
        { en: "sender", vi: "người gửi tin, người truyền tin" },
        { en: "shortage", vi: "sự thiếu hụt" },
        { en: "spacious", vi: "rộng rãi" },
        { en: "temporarily", vi: "tạm thời" },
        { en: "thoroughly", vi: "một cách kỹ lưỡng, tỉ mỉ" },
        { en: "towel", vi: "khăn tắm" },
        { en: "trash", vi: "rác, vật vô giá trị" },
        { en: "unattended", vi: "không được giám sát, không được quan tâm" },
        { en: "usage", vi: "cách sử dụng" },
        { en: "vacuum", vi: "không gian trống/chân không" },
        { en: "windy", vi: "có gió" },
        { en: "wireless", vi: "thiết bị không dây" },
        { en: "yearly", vi: "hàng năm, mỗi năm" },

        // ==================== LIST 9 ====================
        { en: "actress", vi: "diễn viên nữ" },
        { en: "adjacent", vi: "bên cạnh, gần đó" },
        { en: "alternate", vi: "lựa chọn thay thế, người thay thế" },
        { en: "anytime", vi: "bất kỳ thời điểm, thời gian nào" },
        { en: "badge", vi: "huy hiệu, phù hiệu" },
        { en: "boardroom", vi: "phòng họp của ban giám đốc" },
        { en: "brake", vi: "phanh lại, hãm lại" },
        { en: "calculation", vi: "sự tính toán, phép tính" },
        { en: "carpenter", vi: "thợ mộc" },
        { en: "caterer", vi: "người cung cấp thực phẩm" },
        { en: "classify", vi: "phân loại" },
        { en: "congratulate", vi: "chúc mừng" },
        { en: "consultation", vi: "cuộc hội ý, sự bàn bạc" },
        { en: "coordinator", vi: "người phối hợp, điều phối viên" },
        { en: "costly", vi: "đắt tiền, tốn kém" },
        { en: "durable", vi: "lâu bền, bền vững" },
        { en: "equip", vi: "trang bị" },
        { en: "escort", vi: "hộ tống, đi theo" },
        { en: "excursion", vi: "cuộc du ngoạn, chuyến tham quan" },
        { en: "glove", vi: "găng tay" },
        { en: "graphic", vi: "thuộc đồ họa, hình ảnh" },
        { en: "hardware", vi: "đồ kim khí, phần cứng" },
        { en: "inexpensive", vi: "không đắt, rẻ" },
        { en: "inexperience", vi: "sự thiếu kinh nghiệm" },
        { en: "lengthy", vi: "dài (về thời gian hoặc kích thước)" },
        { en: "librarian", vi: "thủ thư" },
        { en: "malfunction", vi: "sự trục trặc, sự hỏng hóc" },
        { en: "mask", vi: "mặt nạ" },
        { en: "meantime", vi: "trong khi chờ đợi" },
        { en: "merge", vi: "kết hợp, hợp nhất" },
        { en: "outdate", vi: "làm cho lỗi thời" },
        { en: "patience", vi: "sự kiên nhẫn" },
        { en: "performer", vi: "người biểu diễn" },
        { en: "pharmacist", vi: "dược sĩ, người bán dược phẩm" },
        { en: "pizza", vi: "bánh pizza" },
        { en: "postcard", vi: "bưu thiếp" },
        { en: "prospective", vi: "có triển vọng" },
        { en: "purchaser", vi: "người mua" },
        { en: "purse", vi: "túi xách tay (của phụ nữ)" },
        { en: "realtor", vi: "người môi giới (mua bán) bất động sản" },
        { en: "rearrange", vi: "sắp xếp lại, bố trí lại" },
        { en: "reopen", vi: "mở cửa lại" },
        { en: "resignation", vi: "sự từ chức" },
        { en: "reviewer", vi: "người phê bình" },
        { en: "revision", vi: "sự soát lại, sửa lại" },
        { en: "soap", vi: "xà phòng" },
        { en: "spokesperson", vi: "người phát ngôn" },
        { en: "strictly", vi: "nghiêm ngặt" },
        { en: "terminate", vi: "kết thúc, chấm dứt" },
        { en: "tomato", vi: "quả cà chua" },
        { en: "translation", vi: "dịch thuật" },
        { en: "tray", vi: "khay để đồ" },
        { en: "unfamiliar", vi: "không quen, lạ lẫm" },
        { en: "vendor", vi: "người bán hàng" },
        { en: "withdrawal", vi: "sự thu hồi, sự rút khỏi" },

        // ==================== LIST 10 ====================
        { en: "accessory", vi: "đồng phạm" },
        { en: "airfare", vi: "tiền máy bay, phí hàng không" },
        { en: "alert", vi: "tỉnh táo, cảnh giác" },
        { en: "assembly", vi: "cuộc tụ tập, cuộc họp, hội đồng" },
        { en: "auditorium", vi: "khán phòng, giảng đường" },
        { en: "bake", vi: "nướng bằng lò" },
        { en: "basket", vi: "giỏ, rổ" },
        { en: "businessperson", vi: "doanh nhân" },
        { en: "celebrity", vi: "người nổi tiếng" },
        { en: "certification", vi: "giấy chứng nhận, chứng chỉ" },
        { en: "closure", vi: "sự đóng cửa (cơ sở kinh doanh)" },
        { en: "considerably", vi: "một cách đáng kể" },
        { en: "deduct", vi: "trừ hoặc lấy đi" },
        { en: "dislike", vi: "không thích, ghét" },
        { en: "disruption", vi: "hành động gián đoạn và gây ra sự hỗn loạn" },
        { en: "downstairs", vi: "tầng dưới" },
        { en: "electrician", vi: "thợ điện" },
        { en: "enthusiastic", vi: "hăng hái, nhiệt tình" },
        { en: "faulty", vi: "bị lỗi, mắc khuyết điểm" },
        { en: "graduation", vi: "lễ tốt nghiệp, sự tốt nghiệp" },
        { en: "hobby", vi: "sở thích" },
        { en: "icy", vi: "đóng băng, băng giá" },
        { en: "informal", vi: "(trang phục) thông thường, thoải mái; (sự kiện) không trang trọng" },
        { en: "irregular", vi: "không đều, không theo quy luật" },
        { en: "kilometer", vi: "kilômét" },
        { en: "lawn", vi: "bãi cỏ" },
        { en: "login", vi: "đăng nhập" },
        { en: "managerial", vi: "thuộc giám đốc; thuộc quản lý" },
        { en: "microscope", vi: "kính hiển vi" },
        { en: "mineral", vi: "khoáng chất" },
        { en: "mislead", vi: "làm cho lạc đường; lừa dối" },
        { en: "misplace", vi: "để nhầm chỗ" },
        { en: "motorcycle", vi: "xe mô tô" },
        { en: "necessity", vi: "vật dụng cần thiết" },
        { en: "newsstand", vi: "quầy bán báo" },
        { en: "overhead", vi: "chi phí cố định của một doanh nghiệp" },
        { en: "planner", vi: "người đặt kế hoạch" },
        { en: "portfolio", vi: "danh mục đầu tư (của công ty, ngân hàng)" },
        { en: "programmer", vi: "lập trình viên" },
        { en: "proofread", vi: "đọc rà soát (để tìm ra lỗi)" },
        { en: "rack", vi: "giá đỡ, kệ để đồ" },
        { en: "recruiter", vi: "nhà tuyển dụng" },
        { en: "remainder", vi: "phần còn lại, phần dư" },
        { en: "remodel", vi: "tu sửa" },
        { en: "rose", vi: "hoa hồng" },
        { en: "statistics", vi: "số liệu thống kê" },
        { en: "statue", vi: "tượng" },
        { en: "steadily", vi: "một cách đều đặn, từ từ" },
        { en: "stockholder", vi: "cổ đông, người góp vốn" },
        { en: "superior", vi: "cấp trên" },
        { en: "tunnel", vi: "đường hầm" },
        { en: "unlimited", vi: "không giới hạn" },
        { en: "vacant", vi: "trống không" },
        { en: "vitamin", vi: "vitamin" },
        { en: "zoo", vi: "sở thú" }
    ];

    window.medQuizFlashcards["Tiếng Anh"] = vocabulary.map((item, index) => ({
        id: `english11-${String(index + 1).padStart(3, "0")}`,
        front: item.en,
        back: item.vi,
        pronunciation: "",
        example: ""
    }));

    console.log(
        `✅ tienganh11.js: đã tải ${window.medQuizFlashcards["Tiếng Anh"].length} từ cho Luyện từ Anh ↔ Việt`
    );
})();
